Correcting Major Bug Report
Some code line has been mistakenly removed. I reinstalled missing code. Corresponding Test == OK
------------------------------
Remaining Tests
-------------------------------------
 ...........F.........E.............
======================================================================
ERROR: test_password_reset_confirm (pur_beurre.test.test_urls.TestUrls)
Testing URL - Password Reset Confirm
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/odin/RAGNAROCK/11_Upgrade&Debug/PurBeurre-P11/pur_beurre/test/test_urls.py", line 61, in test_password_reset_confirm
    response = self.client.get(self.password_reset_confirm_url)
AttributeError: 'TestUrls' object has no attribute 'password_reset_confirm_url'

======================================================================
FAIL: test_Profile (users.test.test_models.TestModels)
Testing the Profile class' object
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/odin/RAGNAROCK/11_Upgrade&Debug/PurBeurre-P11/users/test/test_models.py", line 21, in test_Profile
    self.assertEquals(self.user_1.password,
AssertionError: 'pbkdf2_sha256$180000$ePD8rThYBDtn$4GjcPSVAi0Ks0F1J5xjJ+wtTjvoMyR2w1tSIWZdEuBI=' != 'pbkdf2_sha256$180000$69zRzYujKH2b$+cIBo9b+p81+CMSt/YCm2qCBB5aEtbf7nbaSUFZUCWE='
- pbkdf2_sha256$180000$ePD8rThYBDtn$4GjcPSVAi0Ks0F1J5xjJ+wtTjvoMyR2w1tSIWZdEuBI=
+ pbkdf2_sha256$180000$69zRzYujKH2b$+cIBo9b+p81+CMSt/YCm2qCBB5aEtbf7nbaSUFZUCWE=


----------------------------------------------------------------------
Ran 37 tests in 7.563s

FAILED (failures=1, errors=1)