Correction Bug test_profile
*Solution* **BUG TEST_PROFILE**: The test error was not in the code or app execution but in the test executions. The wrong tests were applied, and therefore tests failed. I corrected the tests.
-------------------------------------------------------------------
Remaining test results:
-----------------------------------------------------------------------
.....................E.............
======================================================================
ERROR: test_password_reset_confirm (pur_beurre.test.test_urls.TestUrls)
Testing URL - Password Reset Confirm
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/odin/RAGNAROCK/11_Upgrade&Debug/PurBeurre-P11/pur_beurre/test/test_urls.py", line 61, in test_password_reset_confirm
    response = self.client.get(self.password_reset_confirm_url)
AttributeError: 'TestUrls' object has no attribute 'password_reset_confirm_url'

----------------------------------------------------------------------
Ran 37 tests in 7.805s

FAILED (errors=1)